### ISSUE TITLE
Seperate / flow functions

### ISSUE THREAD

**Issue by devsjors** [WesselSmit/web-app-from-scratch-1920#13]
I would write a function that generates a form with the triviaSettings as options. When that's filled in I would call the fetchData() function which builds a component with a question and 4 answers and work further from there. 

I would also build a separate function which fills the components with data. This way you can call that function when the component is build after fetching and then when the users continues to the next question you only have to call the function that changes the content of the cards.

**Comment by Razpudding** [comment]
> I would also build a separate function which fills the components with data. This way you can call that function when the component is build after fetching and then when the users continues to the next question you only have to call the function that changes the content of the cards.

That sounds like a great improvement. The creation of a question and answers could each live in their own function.

Also, at first I didnt like the global fetchedData but I think there is something to be said for a global variable which keeps track of fetchedData because later on you might fetch more data and add that.

**Comment by WesselSmit** [comment]
I totally agree with splitting the logic in multiple functions.

For the fetchedData; Razpudding brings up a good point. But my main reason is I want to keep a preserved/copy of the original data object since I plan on creating a modified object with additional data, which will keep track of personal stats.

**Comment by WesselSmit** [comment]
In the code of the concept I've separated the logic for creating HTML and inserting content into the DOM into 2 modules.
